# Generated by Django 5.2.6 on 2025-09-20 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 20, 20, 17, 25, 900617, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='address',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 20, 20, 17, 25, 900617, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 20, 20, 17, 25, 900617, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 20, 20, 17, 25, 900617, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 20, 20, 17, 25, 900617, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 20, 20, 17, 25, 900617, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 20, 20, 17, 25, 900617, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 20, 20, 17, 25, 900617, tzinfo=datetime.timezone.utc)),
        ),
    ]
